create table CAR (
  id IDENTITY primary key,
  brand VARCHAR2(150),
  model VARCHAR2(200),
  power DOUBLE,
  year_of_issue YEAR
);

create table AIRPLANE (
  id IDENTITY primary key,
  brand VARCHAR2(150),
  model VARCHAR2(200),
  manufacturer VARCHAR2(500),
  year_of_issue YEAR,
  FUEL_CAPACITY INT,
  seats INT
);

CREATE TABLE IF NOT EXISTS CAR_ASSESSED_VALUE
(id SERIAL , ASSESSED_DATE TIMESTAMP(26, 6), CAR_ID INT, VALUE DECIMAL);

CREATE TABLE IF NOT EXISTS AIRPLANE_ASSESSED_VALUE
(id SERIAL , ASSESSED_DATE TIMESTAMP(26, 6), AIRPLANE_ID INT, VALUE DECIMAL);